runtime:
  cache_dir: ./.cache/antora
site:
  title: Summit 2023 - GitOps Workshop Guide
  start_page: summit-2023-gitops-workshop-guide:m1-overview:intro.adoc

content:
  sources:
    - url: .
      start_path: docs/

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
  extensions:
  - ./lib/tabs.js

ui:
  bundle:
    url: ./ui/ui-bundle.zip
  supplemental_files: ./ui/supplemental-ui

output:
  dir: ./site
